### ISSUE TITLE
Can we use your code?

### ISSUE THREAD

**Issue by sergeyf** [EthanRosenthal/torchmf#7]
Hello Ethan,

I maintain `fancyimpute` and my goal is to remove dependence on tensorflow and cvxopt. We have a bare-bones MF module (https://github.com/iskandr/fancyimpute/blob/master/fancyimpute/matrix_factorization.py). Do you mind if I replace ours with a bunch of code that is heavily inspired by yours and attribute you?

Thanks,
Sergey

**Comment by EthanRosenthal** [comment]
Sure, have at it!

**Comment by sergeyf** [comment]
Thank you!
